name: Develop PR build

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
